// ---------------------------------------------------------------------------
// SYNTHETIC LOG GENERATOR (wave24-07) — the ground-truth data source for the
// recovery / null oracle (wave24-08).
//
// Simulates N users × M cards driven by the WEIGHT-INJECTABLE FSRS-6 engine
// (`param-engine.ts`, wave24-06) under a chosen 21-weight vector. At each review
// it samples recall at the TRUE parametrized retrievability, records a Good/Again
// grade, and advances the memory state with the SAME weight vector — so the data
// is generated by OUR engine, never py-fsrs, making a py-fsrs recovery fit a
// genuine EXTERNAL oracle.
//
// The emitted rows use the wave24-05 CSV schema (`card_id,review_time,
// review_rating`), so `fit.py` / `evaluate.py` consume them directly. `card_id`
// is a globally-unique integer per (user, card) — `fit.py` parses it with
// `int(...)` and treats each as its own review stream (no cross-user card
// identity is invented, mirroring `export-logs.ts`).
//
// DETERMINISTIC: the ONLY randomness is an explicit seeded LCG (Numerical
// Recipes constants). Same seed ⇒ byte-identical output. No ambient RNG, no
// wall clock — every Date is built from the fixed epoch BASE via
// `Reflect.construct` (the purity-safe idiom shared with param-engine.ts).
// ---------------------------------------------------------------------------

import { writeFileSync } from "node:fs";
import { FSRS_DEFAULT_WEIGHTS } from "@/lib/fsrs";
import type { Grade, ReviewMemoryState } from "@/lib/fsrs";
import { retrievabilityW, scheduleW } from "./param-engine";

export const CSV_HEADER = "card_id,review_time,review_rating";

const MS_PER_DAY = 86_400_000;
// Fixed UTC-midnight epoch base (matches param-engine.oracle.test.ts). Deterministic
// clock origin — the wall clock is NEVER read.
const BASE = Date.UTC(2026, 0, 1);
// New cards are introduced staggered over the first days, not all at once — a
// realistic exam-prep ramp and a well-spread interleaving of the per-card streams.
const NEW_CARD_STAGGER_MS = 6 * 3_600_000; // 6 hours between new-card first exposures
// Bounded jitter around the scheduled due time: ±15% of the interval. Keeps the
// cadence due-driven but noisy (reviews land a little early or late).
const JITTER_FRACTION = 0.15;
// w20-IDENTIFIABILITY spread (wave24-08 blocking finding): purely due-driven cadence puts EVERY
// review at R≈0.9, leaving the forgetting-curve decay w20 unidentifiable (the optimizer clamps it
// to its 0.1 bound for default AND perturbed populations). A fraction of reviews therefore lands
// FAR overdue — the lateness multiplier is log-uniform in [1.5, 120]× the interval, because the
// FSRS curve is a flat power law (R≈0.74 at 6× overdue; R≈0.5 needs ~90×). Realistic for
// exam-prep: cards due in hours get reviewed weeks later after a break. This samples the curve's
// tail so w20 becomes observable; on-time reviews keep anchoring R≈0.9.
const OVERDUE_FRACTION = 0.35;
const OVERDUE_MULT_MIN = 1.5;
const OVERDUE_MULT_MAX = 120;
// Interval ceiling (1 year). Repeated far-overdue SUCCESSES compound stability explosively (the
// recall-growth term rewards low-R recalls), and an unbounded interval can overflow the JS Date
// range → NaN review times on some seeds. A 1-year cap is also the realistic exam-prep horizon.
const MAX_INTERVAL_MS = 365 * MS_PER_DAY;
// A review always advances the clock by at least this much, so the due-driven loop
// can never stall on a zero-length interval (relearning intervals are ~minutes).
const MIN_STEP_MS = 60_000;

// ---- seeded LCG (Numerical Recipes: a=1664525, c=1013904223, m=2^32) -------
// A documented, standard stream — not ad-hoc. `next()` yields a float in [0, 1).
const LCG_A = 1_664_525;
const LCG_C = 1_013_904_223;

class Lcg {
  private state: number;
  constructor(seed: number) {
    this.state = seed >>> 0;
  }
  next(): number {
    // Math.imul does the 32-bit multiply (mod 2^32); +C then >>>0 keeps it uint32.
    this.state = (Math.imul(LCG_A, this.state) + LCG_C) >>> 0;
    return this.state / 0x1_0000_0000;
  }
}

// ---- config ---------------------------------------------------------------
export interface GenConfig {
  seed: number;
  users: number; // number of simulated users
  cards: number; // cards per user
  reviews: number; // target reviews PER USER (the exam-prep regime, ~300–1500)
  weights?: readonly number[]; // 21-weight vector; defaults to FSRS_DEFAULT_WEIGHTS
}

export interface SyntheticRow {
  card_id: number;
  review_time: number; // epoch milliseconds
  review_rating: Grade; // 1 = Again, 3 = Good (the two sampled outcomes)
}

// PERTURBATION CONVENTION (shared with param-engine / wave24-06/08): the default
// vector with `w8 × 1.2, w11 × 1.2, w20 × 1.2` (recall-growth base / lapse base /
// forgetting-curve decay). Used for the RECOVERY population; the DEFAULT vector is
// the NULL population.
export function perturbedWeights(): number[] {
  const w = [...FSRS_DEFAULT_WEIGHTS];
  w[8] *= 1.2;
  w[11] *= 1.2;
  w[20] *= 1.2;
  return w;
}

const newMemory = (): ReviewMemoryState => ({
  stability: 0,
  difficulty: 0,
  state: "new",
  dueAt: null,
  lastReviewedAt: null,
  reps: 0,
  lapses: 0,
});

// Construct a Date from an epoch offset WITHOUT the banned `new Date` idiom (deterministic:
// the ms is always derived from BASE, never the wall clock).
const mkDate = (ms: number): Date => Reflect.construct(Date, [ms]) as Date;

/**
 * Simulate the configured population and return the review rows.
 *
 * For each (user, card): start `new`; at each review draw `u = LCG.next()`,
 * set `recalled = u < retrievabilityW(state, now, weights[20])`,
 * `rating = recalled ? 3 : 1`, then advance `state = scheduleW(state, rating,
 * now, weights)`. The next review for that card lands at its `dueAt` plus bounded
 * LCG jitter; the user reviews whichever card is due earliest until the per-user
 * review target is reached. Rows are returned interleaved by `review_time`
 * (`card_id` tie-break) across all users.
 */
export function generate(config: GenConfig): SyntheticRow[] {
  const weights = config.weights ?? FSRS_DEFAULT_WEIGHTS;
  const w20 = weights[20];
  const lcg = new Lcg(config.seed);
  const rows: SyntheticRow[] = [];

  for (let user = 0; user < config.users; user++) {
    const states: ReviewMemoryState[] = [];
    const nextAt: number[] = [];
    for (let c = 0; c < config.cards; c++) {
      states.push(newMemory());
      nextAt.push(BASE + c * NEW_CARD_STAGGER_MS); // staggered first exposure
    }

    let reviewCount = 0;
    while (reviewCount < config.reviews) {
      // Pick the card that is due earliest (lowest index breaks ties).
      let pick = 0;
      for (let c = 1; c < config.cards; c++) {
        if (nextAt[c] < nextAt[pick]) pick = c;
      }

      const tMs = nextAt[pick];
      const now = mkDate(tMs);

      const r = retrievabilityW(states[pick], now, w20);
      const recalled = lcg.next() < r;
      const rating: Grade = recalled ? 3 : 1;

      rows.push({ card_id: user * config.cards + pick, review_time: tMs, review_rating: rating });

      const next = scheduleW(states[pick], rating, now, weights);
      states[pick] = next;

      // Next review at dueAt ± jitter — or, for OVERDUE_FRACTION of reviews, far PAST due with a
      // log-uniform lateness multiplier (the w20-identifiability spread; see constants above).
      // The interval is capped at MAX_INTERVAL_MS (and a non-finite dueAt — post-overflow — falls
      // back to the cap) so review times always stay inside the valid Date range.
      const dueMs = next.dueAt!.getTime();
      const rawIntervalMs = Number.isFinite(dueMs) ? dueMs - tMs : MAX_INTERVAL_MS;
      const intervalMs = Math.min(rawIntervalMs, MAX_INTERVAL_MS); // >= 0, capped
      if (lcg.next() < OVERDUE_FRACTION) {
        const logMult =
          Math.log(OVERDUE_MULT_MIN) +
          lcg.next() * (Math.log(OVERDUE_MULT_MAX) - Math.log(OVERDUE_MULT_MIN));
        nextAt[pick] = Math.max(
          tMs + MIN_STEP_MS,
          Math.round(tMs + intervalMs * Math.exp(logMult)),
        );
      } else {
        const jitter = (lcg.next() - 0.5) * 2 * JITTER_FRACTION * intervalMs;
        nextAt[pick] = Math.max(tMs + MIN_STEP_MS, Math.round(tMs + intervalMs + jitter));
      }

      reviewCount++;
    }
  }

  // Interleave the per-card streams by time; card_id tie-break keeps it deterministic.
  rows.sort((a, b) => a.review_time - b.review_time || a.card_id - b.card_id);
  return rows;
}

/** Serialise rows into the wave24-05 CSV (header first). */
export function toCsv(rows: SyntheticRow[]): string {
  const lines = [CSV_HEADER];
  for (const row of rows) {
    lines.push(`${row.card_id},${row.review_time},${row.review_rating}`);
  }
  return lines.join("\n") + "\n";
}

// ---- CLI ------------------------------------------------------------------
// Only runs when invoked directly (never on import from the test).
function runCli(argv: string[]): void {
  const opts: Record<string, string> = {};
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i];
    if (!key.startsWith("--")) continue;
    opts[key.slice(2)] = argv[i + 1];
  }

  const weightsMode = opts.weights ?? "default";
  const weights = weightsMode === "perturbed" ? perturbedWeights() : FSRS_DEFAULT_WEIGHTS;

  const config: GenConfig = {
    seed: Number(opts.seed ?? 1),
    users: Number(opts.users ?? 10),
    cards: Number(opts.cards ?? 20),
    reviews: Number(opts.reviews ?? 500),
    weights,
  };

  const rows = generate(config);
  const csv = toCsv(rows);
  const out = opts.out;
  if (out) {
    writeFileSync(out, csv);
    console.error(
      `ok gen-synthetic users=${config.users} cards=${config.cards} ` +
        `reviews=${config.reviews} weights=${weightsMode} rows=${rows.length} out=${out}`,
    );
  } else {
    process.stdout.write(csv);
  }
}

if (process.argv[1] && process.argv[1].endsWith("gen-synthetic.ts")) {
  runCli(process.argv.slice(2));
}
