#!/bin/zsh
cd ~/drivers-school
T="elevated isometric high three-quarter aerial camera, near-orthographic, REALISTIC physically-based materials and surfaces (realistic textured asphalt, real grass and foliage, realistic glossy-matte car paint, refined building facades with real windows), high-end product-visualization realism like a premium 3D studio render, NOT toy, NOT clay, NOT plasticine, NOT low-poly. Soft realistic studio daylight, soft natural shadows, low contrast, calm palette with sparing road-sign blue, lane amber and signal green accents, crisp sharp detail, octane/redshift quality, no words or letters on signs, 1:1, no watermark"
: > .content-import/style_links_real.txt
node .content-import/gen_demo_image.mjs "Photorealistic premium 3D render of a complete road intersection scene filling the entire frame edge to edge — a continuous realistic little world: textured asphalt roads to all edges, real grass blocks with realistic trees on the corners, a few small realistic buildings, a small blue car at the intersection, a traffic light and blue and amber road signs, warm off-white sky between buildings. $T" real_world max 2>&1 | tail -1
url=$(curl -s --max-time 40 -F "reqtype=fileupload" -F "fileToUpload=@public/demo-images/real_world.png" https://catbox.moe/user/api.php); echo "realism_world -> $url" | tee -a .content-import/style_links_real.txt
node .content-import/gen_demo_image.mjs "Photorealistic premium 3D render of a clean four-way road intersection filling the entire frame edge to edge, realistic textured asphalt and lane markings, neat realistic grass verges with a few trees, a small blue car, a realistic traffic light and blue/amber signs, one tidy modern building, warm soft daylight. $T" real_clean max 2>&1 | tail -1
url=$(curl -s --max-time 40 -F "reqtype=fileupload" -F "fileToUpload=@public/demo-images/real_clean.png" https://catbox.moe/user/api.php); echo "realism_clean -> $url" | tee -a .content-import/style_links_real.txt
echo DONE
