import { describe, it, expect } from "vitest";

import { runCell, type CellParams } from "@/lib/exam-allocator-sim";

// REPRODUCIBILITY PIN (spec `specs/wave23-exam-allocator-spike.md`, Deliverable 3,
// second half) — NOT a correctness oracle.
//
// This test does NOT re-verify the allocator's CORRECTNESS (that is the
// wave23-01→04 chain: the python reference + `lib/exam-allocator.oracle.test.ts`).
// It pins the sim's DETERMINISM byte-exactly: the same seed → the same numbers,
// so the wave23-07 measurement report's figures can be regenerated by anyone.
// Self-consistency is the correct discipline here — the frozen literal IS
// whatever seed-42 yields; the tsx measurement runner and this test share ONE
// code path (the exported `runCell`), so a divergence between "what the report
// ran" and "what the test pins" is impossible.
//
// The numbers below were CAPTURED from the real `runCell(CELL, 42)` run at
// authoring time (2026-07-14, via `npx tsx`). Re-run that same call to reproduce.
const CELL: CellParams = { prior: "median", horizonDays: 14, budget: 15, replicas: 5 };
const SEED = 42;

// Frozen seed-42 output of `runCell(CELL, 42)` (≥6 significant digits).
const BASELINE_MEAN = 0.5702272394905409;
const ALLOCATOR_MEAN = 0.5663572662013813;
const LIFT_MEAN = -0.003869973289159534;
const LIFT_SE = 0.011900805030150747;
const LIFT_CI_LOW = -0.027195551148255;
const LIFT_CI_HIGH = 0.01945560456993593;

describe("exam-allocator-sim determinism (seed 42 reproducibility pin)", () => {
  it("reproduces the frozen seed-42 cell output byte-exactly", () => {
    const r = runCell(CELL, SEED);
    expect(r.baselineMean).toBe(BASELINE_MEAN);
    expect(r.allocatorMean).toBe(ALLOCATOR_MEAN);
    expect(r.liftMean).toBe(LIFT_MEAN);
    expect(r.liftSE).toBe(LIFT_SE);
    expect(r.liftCiLow).toBe(LIFT_CI_LOW);
    expect(r.liftCiHigh).toBe(LIFT_CI_HIGH);
  });

  it("is stable across repeated runs (same seed → identical output)", () => {
    const a = runCell(CELL, SEED);
    const b = runCell(CELL, SEED);
    expect(JSON.stringify(b)).toBe(JSON.stringify(a));
  });
});
