// ---------------------------------------------------------------------------
// Pure, deterministic ONE-FACTOR Gauss–Hermite ICC mixture (Deliverable 3).
// No DB, no clock, no randomness.
//
// The independence readiness dial (lib/readiness-model.ts) treats every exam
// slot as an INDEPENDENT Bernoulli trial. Real answers within a topic are
// correlated: a student who is "having a good day" (or has a systematically
// mis-calibrated grasp of a theme) shifts EVERY slot the same direction. We
// model that as ONE shared latent standard-normal factor `Z ~ N(0,1)` acting on
// the LOGIT scale — per slot `p → sigmoid(logit(p) + σ·Z)` — with the factor
// scale `σ = σ₀·w(evidence)` DECAYING as review mass accrues (rich evidence ⇒
// the shared nuisance shrinks ⇒ the mixture releases back to independence).
//
// The intractable integral over `Z` is a Gauss–Hermite quadrature: at each of
// `nNodes` standard-normal nodes `z_i` the whole p-vector is logit-shifted by
// `σ·z_i`, the EXISTING exact Poisson-binomial DP runs UNCHANGED per node, and
// `mixtureDial` is the node-weight-normalised average of the per-node pass
// probabilities. The ICC lives OUTSIDE the PB recursion (an input-side mixture),
// never inside it — so `poissonBinomialAtLeast` is reused verbatim.
//
// Every design constant (nNodes, ρ, σ₀, the decay form, the node/weight table)
// is PINNED by the wave19d-02 oracle
// (lib/readiness-factor-mixture.oracle.test.ts, generated by
// scripts/oracles/gen-19d-oracles.py from specs/wave19d-blueprint-and-release.md
// Deliverable 3). This module MATCHES those literals; it does not invent them.
//
// The outer `min(mixtureDial, independenceDial)` never-above guarantee and the
// seen/unseen assembly are OTHER modules (wave19d-07/05/08) — this file returns
// `mixtureDial` only.
// ---------------------------------------------------------------------------

import { poissonBinomialAtLeast } from "./readiness-model";

/** Number of Gauss–Hermite nodes (research: "~20 nodes"; pinned by the oracle). */
export const N_NODES = 20;

/** Within-topic intraclass correlation ρ (logistic-normal latent-ICC map). */
export const RHO = 0.35;

/**
 * Latent factor scale at zero evidence, from the standard logistic-normal ICC
 * map `ρ = σ₀²/(σ₀² + π²/3)` ⇒ `σ₀ = √(ρ/(1−ρ)·π²/3)` (π²/3 = Var of the
 * standard logistic). Evaluates to ≈ 1.33096485927 for ρ = 0.35.
 */
export const SIGMA0 = Math.sqrt((RHO / (1 - RHO)) * ((Math.PI * Math.PI) / 3));

/** Pseudo-count of prior review mass in the evidence decay (M0 = 1). */
export const EVIDENCE_M0 = 1;

/** Logit clamp so a `p` at the 0/1 boundary stays finite (mirrors the oracle). */
const LOGIT_EPS = 1e-12;

// Gauss–Hermite (probabilists' HermiteE, weight e^{-x²/2}) nodes + weights for
// the N(0,1) factor, for `N_NODES = 20`. These are an EXTERNAL mathematical
// constant — the exact output of numpy.polynomial.hermite_e.hermegauss(20),
// pinned verbatim by the wave19d-02 oracle. The 20-node HermiteE quadrature is
// a fixed table (like any Gaussian-quadrature rule); the weights sum to √(2π)
// and, normalised by √(2π), sum to 1 so `mixtureDial` is a proper average.
const GH20_NODES: readonly number[] = [
  -7.61904854167976, -6.51059015701365, -5.5787388058932, -4.73458133404606,
  -3.94396735065732, -3.18901481655339, -2.45866361117237, -1.74524732081413,
  -1.04294534880275, -0.346964157081356, 0.346964157081356, 1.04294534880275,
  1.74524732081413, 2.45866361117237, 3.18901481655339, 3.94396735065732,
  4.73458133404606, 5.5787388058932, 6.51059015701365, 7.61904854167976,
];
const GH20_WEIGHTS: readonly number[] = [
  3.15283872938279e-13, 6.22160769677664e-10, 1.53593403381993e-07,
  1.10344811931221e-05, 0.000322919595868101, 0.00458738825385709,
  0.035087375128592, 0.154173611285539, 0.405420387684281, 0.65371126667029,
  0.65371126667029, 0.405420387684281, 0.154173611285539, 0.035087375128592,
  0.00458738825385709, 0.000322919595868101, 1.10344811931221e-05,
  1.53593403381993e-07, 6.22160769677664e-10, 3.15283872938279e-13,
];

/** Gauss–Hermite (probabilists' HermiteE) rule for the N(0,1) factor. */
export interface GaussHermiteRule {
  /** Quadrature nodes `z_i` (symmetric about 0). */
  nodes: number[];
  /** Raw HermiteE weights (weight e^{-x²/2}; sum to √(2π)). */
  weights: number[];
  /** Weights ÷ √(2π) — the N(0,1) normalisation; sum to 1. */
  normWeights: number[];
}

/**
 * Gauss–Hermite (probabilists' HermiteE) nodes + weights for the standard-normal
 * factor. Only `N_NODES` (20) is supported — the fixed table pinned by the
 * oracle. `normWeights = weights / √(2π)` so they sum to 1, making the mixture a
 * proper node-weighted average.
 */
export function gaussHermite(n: number): GaussHermiteRule {
  if (n !== N_NODES) {
    throw new Error(`gaussHermite: only N_NODES=${N_NODES} is supported (got ${n})`);
  }
  const norm = Math.sqrt(2 * Math.PI);
  const nodes = GH20_NODES.slice();
  const weights = GH20_WEIGHTS.slice();
  const normWeights = weights.map((w) => w / norm);
  return { nodes, weights, normWeights };
}

/**
 * Factor scale from accumulated review mass `M` (integer ≥ 0): the O(M^−1/2)
 * credible-gap decay `σ(M) = σ₀·√(M0/(M0+M))`. As evidence grows the shared
 * nuisance shrinks toward 0, releasing the mixture back to independence.
 */
export function sigmaFromEvidence(M: number): number {
  const m = Math.max(0, M);
  return SIGMA0 * Math.sqrt(EVIDENCE_M0 / (EVIDENCE_M0 + m));
}

function clamp01(x: number): number {
  if (x < 0) return 0;
  if (x > 1) return 1;
  return x;
}

/** `logit(p)` with a finite clamp at the 0/1 boundary (mirrors the oracle). */
function logit(p: number): number {
  const q = Math.min(1 - LOGIT_EPS, Math.max(LOGIT_EPS, p));
  return Math.log(q / (1 - q));
}

function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

/**
 * `mixtureDial(pSlots, threshold, sigma)` — the honest pass probability under
 * the shared logit-normal factor. At each Gauss–Hermite node `z_i` every slot's
 * logit is shifted by `sigma·z_i` (`p → sigmoid(logit(p) + sigma·z_i)`), the
 * EXACT Poisson-binomial `P(≥ threshold)` runs UNCHANGED per node, and the
 * result is the node-weight-normalised average `Σ_i normW_i · PB_i`.
 *
 * As `sigma → 0` (rich evidence) every node collapses to the unshifted vector
 * and the result → the plain independence PB. For an above-threshold-mean
 * fixture a larger `sigma` (thin evidence) strictly LOWERS the dial — the shared
 * nuisance concentrates mass away from the near-certain upper tail.
 */
export function mixtureDial(pSlots: number[], threshold: number, sigma: number): number {
  const { nodes, normWeights } = gaussHermite(N_NODES);
  const logits = pSlots.map((p) => logit(clamp01(p)));
  let total = 0;
  for (let i = 0; i < nodes.length; i++) {
    const shift = sigma * nodes[i];
    const shifted = logits.map((l) => sigmoid(l + shift));
    total += normWeights[i] * poissonBinomialAtLeast(threshold, shifted);
  }
  return clamp01(total);
}
