import { describe, it, expect } from "vitest";
import { computeStudyPlan } from "@/lib/study-plan";

// FROZEN ORACLE for the Wave 21 study-plan HONESTY model (reviewLoad flow).
//
// Every literal below is transcribed VERBATIM from the stdlib-only python
// reference oracle captured at
//   tasks/wave21-01-python-oracle/PREVERIFY-OUTPUT.txt
// (generated by scripts/oracles/gen-wave21-oracles.py from
//  specs/wave21-plan-honesty.md + docs/research/PLAN-REVALIDATION-2026-07-14.md).
// DO NOT regenerate these values from the TS impl, and later tasks (03 impl,
// 04 un-skip) may NOT edit them — this authors the golden values only.
//
// The impl-dependent census was suspended while `computeStudyPlan` did not yet
// accept a `reviewLoad` field on `StudyPlanInput`. Task wave21-03 implemented
// it and task wave21-04 activated this suite (removed the suspension + the
// dynamic import scaffolding, restoring a normal static import). One impl-free
// self-consistency test below grades the frozen numbers only.

// Sustainable daily ceiling — frozen literal (mirrors MAX_DAILY_QUOTA in the
// python oracle header). Kept local so the self-consistency test is impl-free.
const FROZEN_MAX_DAILY_QUOTA = 40;

const TODAY = "2026-07-02";

// ---- (a) quota/feasible/daysLeft census (todayKey 2026-07-02) ---------------
// Each row: the computeStudyPlan input + the frozen expected numerics.
// examDate = TODAY + daysLeft; reviewLoad is the new FLOW field.
const CENSUS = [
  { name: "nodate", examDate: null, dueCount: 10, unseenCount: 100, defaultGoal: 15, reviewLoad: 3, quota: 15, feasible: true, daysLeft: null },
  { name: "pace", examDate: "2026-07-12", dueCount: 20, unseenCount: 100, defaultGoal: 15, reviewLoad: 2, quota: 12, feasible: true, daysLeft: 10 },
  { name: "priori", examDate: "2026-07-04", dueCount: 10, unseenCount: 190, defaultGoal: 15, reviewLoad: 5, quota: 40, feasible: false, daysLeft: 2 },
  { name: "maint", examDate: "2026-07-12", dueCount: 50, unseenCount: 0, defaultGoal: 15, reviewLoad: 8, quota: 8, feasible: true, daysLeft: 10 },
  { name: "explode", examDate: "2026-07-05", dueCount: 200, unseenCount: 0, defaultGoal: 15, reviewLoad: 45, quota: 45, feasible: true, daysLeft: 3 },
  { name: "today_ok", examDate: "2026-07-02", dueCount: 5, unseenCount: 5, defaultGoal: 15, reviewLoad: 0, quota: 10, feasible: true, daysLeft: 0 },
  { name: "today_over", examDate: "2026-07-02", dueCount: 10, unseenCount: 20, defaultGoal: 15, reviewLoad: 0, quota: 30, feasible: false, daysLeft: 0 },
  { name: "today_clamp", examDate: "2026-07-02", dueCount: 100, unseenCount: 50, defaultGoal: 15, reviewLoad: 0, quota: 40, feasible: false, daysLeft: 0 },
  { name: "fresh", examDate: "2026-07-12", dueCount: 0, unseenCount: 100, defaultGoal: 15, reviewLoad: 0, quota: 10, feasible: true, daysLeft: 10 },
  { name: "maint0", examDate: "2026-07-07", dueCount: 0, unseenCount: 0, defaultGoal: 15, reviewLoad: 0, quota: 0, feasible: true, daysLeft: 5 },
] as const;

// ---- (c) monotonicity in daysLeft — fixed U=100, reviewLoad=2, G=15 ---------
// examDate = TODAY + daysLeft for daysLeft ∈ [1,2,5,10,20,100].
const MONOTONE_DAYS = [1, 2, 5, 10, 20, 100] as const;
const MONOTONE_EXAM_DATES = [
  "2026-07-03",
  "2026-07-04",
  "2026-07-07",
  "2026-07-12",
  "2026-07-22",
  "2026-10-10",
] as const;
// Displayed (clamped) quota sequence — the honest UI value at each daysLeft.
const MONOTONE_DISPLAYED = [40, 40, 22, 12, 7, 3] as const;

// ═════════════════════════════════════════════════════════════════════════════
// Impl-INDEPENDENT self-consistency of the frozen literals themselves.
// Grades the golden numbers, NOT the (not-yet-written) implementation, so it
// keeps this file collected by `npx vitest list` while the impl block is
// suspended.
// ═════════════════════════════════════════════════════════════════════════════
describe("study-plan honesty oracle — frozen-literal self-consistency", () => {
  it("(c) displayed monotone sequence is non-increasing", () => {
    for (let i = 1; i < MONOTONE_DISPLAYED.length; i++) {
      expect(MONOTONE_DISPLAYED[i]).toBeLessThanOrEqual(MONOTONE_DISPLAYED[i - 1]);
    }
  });

  it("(b) MAINT is exempt from the clamp — explode literal 45 > MAX_DAILY_QUOTA 40", () => {
    const explode = CENSUS.find((r) => r.name === "explode")!;
    expect(explode.quota).toBe(45);
    expect(explode.quota).toBeGreaterThan(FROZEN_MAX_DAILY_QUOTA);
  });

  it("(a) fresh-user quota 10 equals the old one-shot formula ceil(100/10)", () => {
    const fresh = CENSUS.find((r) => r.name === "fresh")!;
    expect(fresh.quota).toBe(10);
    expect(fresh.quota).toBe(Math.ceil(100 / 10));
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// Impl-DEPENDENT census — the `reviewLoad` model landed in wave21-03, so this
// block now runs against the real `computeStudyPlan` via the static import.
// ═════════════════════════════════════════════════════════════════════════════
describe("computeStudyPlan honesty model (reviewLoad) — frozen census", () => {
  it("(a) quota / feasible / daysLeft census", () => {
    for (const row of CENSUS) {
      const plan = computeStudyPlan({
        examDate: row.examDate,
        todayKey: TODAY,
        dueCount: row.dueCount,
        unseenCount: row.unseenCount,
        defaultGoal: row.defaultGoal,
        reviewLoad: row.reviewLoad,
      });
      expect(plan.dailyQuota, `${row.name}.dailyQuota`).toBe(row.quota);
      expect(plan.feasible, `${row.name}.feasible`).toBe(row.feasible);
      expect(plan.daysLeft, `${row.name}.daysLeft`).toBe(row.daysLeft);
    }
  });

  it("(b) clamp — infeasible unseen-work quota ≤ MAX; MAINT exempt", () => {
    const priori = computeStudyPlan({
      examDate: "2026-07-04",
      todayKey: TODAY,
      dueCount: 10,
      unseenCount: 190,
      defaultGoal: 15,
      reviewLoad: 5,
    });
    expect(priori.dailyQuota).toBeLessThanOrEqual(FROZEN_MAX_DAILY_QUOTA);
    expect(priori.dailyQuota).toBe(40);

    const explode = computeStudyPlan({
      examDate: "2026-07-05",
      todayKey: TODAY,
      dueCount: 200,
      unseenCount: 0,
      defaultGoal: 15,
      reviewLoad: 45,
    });
    expect(explode.dailyQuota).toBe(45);
  });

  it("(c) displayed quota is monotone non-increasing in daysLeft (U=100, reviewLoad=2)", () => {
    const displayed = MONOTONE_EXAM_DATES.map(
      (examDate) =>
        computeStudyPlan({
          examDate,
          todayKey: TODAY,
          dueCount: 0,
          unseenCount: 100,
          defaultGoal: 15,
          reviewLoad: 2,
        }).dailyQuota,
    );
    expect(displayed).toEqual([...MONOTONE_DISPLAYED]);
    // Frozen day sequence sanity — the census dates line up with daysLeft.
    expect(MONOTONE_EXAM_DATES.length).toBe(MONOTONE_DAYS.length);
  });
});
